name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm clean-install

      - name: Run ESLint
        run: npx eslint . --ext ts,tsx

      - name: Run tests
        run: npm test
        env:
          CI: true
